# Generated by Django 3.1.4 on 2021-03-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckblues', '0002_feedback_feedbackcomment_post_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='published',
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
