# Generated by Django 3.1.4 on 2021-03-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckblues', '0004_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
