# Generated by Django 3.1.4 on 2021-03-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckblues', '0006_feedback_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='note',
            field=models.TextField(max_length=512),
        ),
    ]
