# Generated by Django 3.1.4 on 2021-03-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckblues', '0007_auto_20210323_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='videoResponse',
            field=models.URLField(blank=True),
        ),
    ]
