# Generated by Django 3.1.4 on 2021-04-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckblues', '0008_auto_20210324_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headerImage',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
